### ISSUE TITLE
Fix 'switch without "default" clause.' issue in OpenDrone-app\mobile\src\main\java\at\opendrone\opendrone\FlightPlaner.java

### ISSUE THREAD

**Issue by tklecka** [OpenDroneAT/OpenDrone#10]
[CodeFactor](https://www.codefactor.io/repository/github/opendroneat/opendrone/overview/develop) found an issue: switch without "default" clause.

It's currently on:
[OpenDrone-app\mobile\src\main\java\at\opendrone\opendrone\FlightPlaner.java:148
](https://www.codefactor.io/repository/github/opendroneat/opendrone/source/develop/OpenDrone-app/mobile/src/main/java/at/opendrone/opendrone/FlightPlaner.java#L148)

**Comment by MarkusKurzmann** [comment]
Closed with pull-request "Worked on Issues"
