### ISSUE TITLE
Internet access via WiFi

### ISSUE THREAD

**Issue by tklecka** [OpenDroneAT/OpenDrone#82]
**Is your feature request related to a problem? Please describe.**
When i connect to the Wifi i do not have Internet access

**Describe the solution you'd like**
INTERNET!!

**Describe alternatives you've considered**
There are no alternatives

**Additional context**
Thanks 
👌

**Comment by michaelhitzker** [comment]
let's see what we can do here!

**Comment by michaelhitzker** [comment]
done in new push
